### ISSUE TITLE
Exam sync to bottlenose generates ugly YAML

### ISSUE THREAD

**Issue by blerner** [CodeGrade/hourglass#222]
E.g.
```
---
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  name: "<p>Pies\t</p>"
  parts:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    name: "<p>Examples</p>"
    weight: 2
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    name: "<p>Templates</p>"
    weight: 9
```

Clean up the HTML, and/or make the column headers be richer HTML, and get rid of the !ruby/hash stuff.
